### ISSUE TITLE
add detail on terrafile usage

### ISSUE THREAD

**Issue by Grummfy** [boltops-tools/terraspace-docs#12]
Hello,
in the documentation of terrafile usage, there is example about using the provided example, but not how to use it from the module.

So is this proper usage?

Terrafile
```
mod "foo", source: "git@gitlab.com:bar/baz.git"
```
```terraform
module "stuff" {
  source = "vendor/modules/foo"
}
```

If yes, add this example could be a nice usage.

**Comment by tongueroo** [comment]
Added example: https://github.com/boltops-tools/terraspace-docs/commit/318d66055a48d57ed730daf385d4248304db940f
