### ISSUE TITLE
gitlab as backend for states file

### ISSUE THREAD

**Issue by Grummfy** [boltops-tools/terraspace-docs#16]
Hello,
I don't really know where to put an example about gitlab, but this is how I do it

See https://docs.gitlab.com/ee/user/infrastructure/terraform_state.html for more information

To use inside gitlab-ci and locally, I have done his configuration
`config/boot.rb`:
```
ENV['CI_PROJECT_ID'] ||= '<your project id>'
ENV['CI_API_V4_URL'] ||= 'https://gitlab.com/api/v4'
ENV['CI_JOB_USERNAME'] ||= 'gitlab-ci-token'
ENV['CI_JOB_TOKEN'] ||= 'you-must-defined-a-gitlab-PAT'
ENV['TF_URL'] = "#{ENV['CI_API_V4_URL']}/projects/#{ENV['CI_PROJECT_ID']}/terraform/state"
```

`test/config/terraform/backend.tf`:
```
terraform {
  backend "http" {
    address = "<%= ENV['TF_URL'] %>/<%= expansion(':ACCOUNT-:REGION-:ENV-:TYPE_DIR-:MOD_NAME') %>"
    lock_address = "<%= ENV['TF_URL'] %>/<%= expansion(':ACCOUNT-:REGION-:ENV-:TYPE_DIR-:MOD_NAME') %>/lock"
    unlock_address = "<%= ENV['TF_URL'] %>/<%= expansion(':ACCOUNT-:REGION-:ENV-:TYPE_DIR-:MOD_NAME') %>/lock"
    username = "<%= ENV['CI_JOB_USERNAME'] %>"
    password = "<%= ENV['CI_JOB_TOKEN'] %>"
    lock_method = "POST"
    unlock_method = "DELETE"
    retry_wait_min = 5
  }
}
```

Note:
* `CI_PROJECT_ID`, `CI_API_V4_URL` and `CI_JOB_TOKEN` is defined by gitlab automatically in the gitlab-ci, it's only for local usage that I define it ;)

**Comment by tongueroo** [comment]
Handled as part of https://github.com/boltops-tools/terraspace-docs/pull/22  Put it under:

https://terraspace.cloud/docs/config/backend/examples/gitlab/

It's based on your example and https://github.com/boltops-tools/terraspace/issues/160

Thanks!
